### ISSUE TITLE
fork后更改config，自动编译出错

### ISSUE THREAD

**Issue by wclmgcd** [ffuqiangg/build_openwrt#2]
错误：
The workflow is not valid. .github/workflows/build-openwrt.yml (Line: 165, Col: 11): Unrecognized named-value: 'success'. Located at position 71 within expression: steps.codes.outputs.package_repo == 'ophub' && env.PACKAGED_STATUS == success

lede和immortalwrt-master都出现

**Comment by ffuqiangg** [comment]
语法错误 success 忘了引号，还有 diy2.sh 也有处语法错误已经一并修复了。
