### ISSUE TITLE
还是不成功，麻烦大佬看看

### ISSUE THREAD

**Issue by wclmgcd** [ffuqiangg/build_openwrt#3]
问题出在这一步
Upload firmware to release：
Run ncipollo/release-action@main
  with:
    tag: lede-2023.08.13-0154
    bodyFile: release.txt
    artifacts: /opt/openwrt_packit/output/*
  
    generateReleaseNotes: false
    makeLatest: legacy
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true
    skipIfReleaseExists: false
    token: ***
    updateOnlyUnreleased: false
  env:
    FEEDS_CONF: config/lede/feeds.conf.default
    CONFIG_FILE: config/lede/config
    DIY1_SH: config/lede/diy1.sh
    DIY2_SH: config/lede/diy2.sh
    TZ: Asia/Shanghai
    COMPILE_DATE: R23.08.12
    PACKAGED_OUTPUTPATH: /opt/openwrt_packit/output
    PACKAGED_OUTPUTDATE: 08.13.0154
    PACKAGED_STATUS: success
    GITHUB_TOKEN: 
Error: Error 403: Resource not accessible by integration

**Comment by wclmgcd** [comment]
用的是大雕的源，我看你说明中还要修改那些，请大佬一并说明

**Comment by ffuqiangg** [comment]
> 用的是大雕的源，我看你说明中还要修改那些，请大佬一并说明

是不是没有 GH_TOKEN

**Comment by wclmgcd** [comment]
这个要如何设置？

**Comment by wclmgcd** [comment]
GH_TOKEN是开发者设置里的Personal access tokens (classic)吗？
我原来用另一个自动编译配置里面可以成功，这里也有GITHUB_TOKEN，
 - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: ${{ env.PACKAGED_STATUS == 'success' }} && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: OpenWrt_${{ env.PACKAGED_OUTPUTDATE }}
        files: ${{ env.PACKAGED_OUTPUTPATH }}/*.img.xz
        body: |
          首次使用建议全新刷写
          * 基本信息
          IP: 192.168.1.2
          账户: root
          密码: password

**Comment by ffuqiangg** [comment]
> 

这个仓库有添加 token 吗？注意命名和 build-openwrt.yml 文件中是否一致。

**Comment by ffuqiangg** [comment]
![Snipaste_2023-08-13_14-20-30](https://github.com/ffuqiangg/build_openwrt/assets/34062439/e195aa3b-ad16-414c-a3cf-bdcce5a76eae)
不想麻烦直接删除 build-openwrt.yml 文件中 234，235 这两行其实也可以。

**Comment by wclmgcd** [comment]
感谢大佬

**Comment by wclmgcd** [comment]
> > 
> 
> 这个仓库有添加 token 吗？注意命名和 build-openwrt.yml 文件中是否一致。
 大佬，如何添加token？是直接把Secrets.GITHUB_TOKEN改成ghp_xxxxxxxxxxxxxxxxxxxxxx？

**Comment by ffuqiangg** [comment]
> > > 
> > 
> > 
> > 这个仓库有添加 token 吗？注意命名和 build-openwrt.yml 文件中是否一致。
> > 大佬，如何添加token？是直接把Secrets.GITHUB_TOKEN改成ghp_xxxxxxxxxxxxxxxxxxxxxx？

仓库的 settings > secrets > actions 里面添加 name 写 GH_TOKEN ，secret 填 ghp_xxx

**Comment by ffuqiangg** [comment]
> > > 
> > 
> > 
> > 这个仓库有添加 token 吗？注意命名和 build-openwrt.yml 文件中是否一致。
> > 大佬，如何添加token？是直接把Secrets.GITHUB_TOKEN改成ghp_xxxxxxxxxxxxxxxxxxxxxx？

这是 Smith 写的 github actions 申请和设置 github_token 的文档，挺详细的。还没搞懂的话去看看应该就明白了。
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#2-%E8%AE%BE%E7%BD%AE%E9%9A%90%E7%A7%81%E5%8F%98%E9%87%8F-github_token
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#3-fork-%E4%BB%93%E5%BA%93%E5%B9%B6%E8%AE%BE%E7%BD%AE-gh_token

**Comment by wclmgcd** [comment]
太怪了，我设置好github_token后，同样的配置居然超时了，fork其他的只是修改config，也是超时，大佬可以帮我编译一个吗？把ip修改成192.168.1.2，app只要passwall，openclash，luci-app-amlogic，luci-app-unblockmusic，

**Comment by ffuqiangg** [comment]
> 太怪了，我设置好github_token后，同样的配置居然超时了，fork其他的只是修改config，也是超时，大佬可以帮我编译一个吗？把ip修改成192.168.1.2，app只要passwall，openclash，luci-app-amlogic，luci-app-unblockmusic，

检查日志，大概率是 luci-app-unblockmusic 需要编译 node，node 编译非常耗时间。

**Comment by wclmgcd** [comment]
luci-app-unblockmusic 我是用的go版，主要是就是在发布那一步失败后，再次重新编译，就出现超时

**Comment by ffuqiangg** [comment]
> luci-app-unblockmusic 我是用的go版，主要是就是在发布那一步失败后，再次重新编译，就出现超时

我看了你的 config，的确是有编译 node。你去 actions 日志页面点击右边的齿轮选择 view raw logs，然后对比时间戳看看是哪一步编译用时太多，然后调整 config，超时没有其它办法解决。
还有 actions 每次分配的服务器 cpu 是不一样的，所以同样的配置这次 5 小时 40 分能完成，下次可能就要 6 小时以上造成超时。

**Comment by wclmgcd** [comment]
感谢大佬，终于成功了
