### ISSUE TITLE
安装docker容器提示空间不足

### ISSUE THREAD

**Issue by lllAlex2333** [ffuqiangg/build_openwrt#5]
docker: write /mnt/sda4/docker/tmp/GetImageBlob2504080284: no space left on device.

使用的是您最新编译的openwrt 23.05 固件，N1盒子

**Comment by ffuqiangg** [comment]
2024.11.28 的固件？那个我是用来测试的，我还没上机我也不知道哪儿会出问题。

**Comment by ffuqiangg** [comment]
> docker: write /mnt/sda4/docker/tmp/GetImageBlob2504080284: no space left on device.
> 
> 使用的是您最新编译的openwrt 23.05 固件，N1盒子

/mnt/sda4 分区的话应该是用 U 盘跑的吧？提示 no space left on device 意思是 /mnt/sda4 这个分区空间不足。可以用 df -h 命令查看各个分区的使用情况。

**Comment by ffuqiangg** [comment]
> 是写入emmc后运行的，df -h 信息如下，看了一下，好像docker目录默认分配的空间太小了。 Filesystem Size Used Available Use% Mounted on udev 512.0K 0 512.0K 0% /dev tmpfs 180.1M 936.0K 179.2M 1% /run /dev/mmcblk2p2 512.0M 402.9M 44.8M 90% / tmpfs 900.6M 4.7M 895.9M 1% /tmp tmpfs 512.0K 0 512.0K 0% /dev cgroup 900.6M 0 900.6M 0% /sys/fs/cgroup /dev/mmcblk2p4 5.3G 1.4M 5.0G 0% /mnt/mmcblk2p4 /dev/mmcblk2p1 511.0M 128.5M 382.5M 25% /boot /dev/mmcblk2p3 512.0M 3.4M 499.0M 1% /mnt/mmcblk2p3 /dev/mmcblk2p2 512.0M 402.9M 44.8M 90% /mnt/sda4/docker

我上机看了下，打包仓库可能有点儿问题挂载乱了。你可以先手动到 dockerman 的设置里把 Docker 根目录那里改成 `/mnt/mmcblk2p4/docker`。然后重启一下 docker 应该就可以了。

**Comment by ffuqiangg** [comment]
> 好的，谢谢！

安全起见可以顺便用 `umount /mnt/sda4/docker` 命令把之前的错误挂载点删了。

**Comment by lllAlex2333** [comment]
> 安全起见可以顺便用 `umount /mnt/sda4/docker` 命令把之前的错误挂载点删了。

OK
