### ISSUE TITLE
关于流量问题

### ISSUE THREAD

**Issue by mogen918** [ffuqiangg/build_openwrt#6]
很感谢作者的无私付出，我已经刷好n1盒子并配置好homeproxy。但是老是在面板里面看到一个套了cdn的域名的信息。不知道什么意思，是固件问题还是软件的问题？如图
![Uploading 82A2EADE31A8EA2C0F582AB08B9BD81B.png…]()

**Comment by ffuqiangg** [comment]
我只是编译的时候选上而已，它是怎么运作的我也不知道。😅
而且我也不怎么用 homeproxy。
